DROP DATABASE IF EXISTS jubileueventos;
CREATE DATABASE jubileueventos;

USE jubileueventos;

DROP TABLE IF EXISTS Usuarios;
CREATE TABLE Usuarios(
id INT AUTO_INCREMENT PRIMARY KEY,
nomeUsuario VARCHAR(255) UNIQUE NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
senha VARCHAR(255) NOT NULL,
tipoUsuario CHAR(1) NOT NULL,
registroCriado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Eventos;
CREATE TABLE Eventos (
id INT AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(255) NOT NULL,
descricao TEXT,
LOCAL VARCHAR(255),
dataEvento DATE,
registroCriado TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Participantes;
CREATE TABLE Participantes (
idUsuario INT NOT NULL,
idEvento INT NOT NULL,
registroCriado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (idUsuario, idEvento),
FOREIGN KEY (idEvento) REFERENCES Eventos(id) ON DELETE CASCADE,
FOREIGN KEY (idUsuario) REFERENCES usuarios(id) ON DELETE CASCADE
);